---
title: "Visualization of subject patient profiles"
subtitle: "GLPG2737-CL-202"
author: "Laure Cougnaud"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: rmarkdown::pdf_document
---

```{r loadData}

	pathData <- file.path(
		"../data/GLPG2737-CL-202-UNBLINDED/SDTM",
		c("CRG10GLP01_SDTM_2018_06JUN_15_v2", "CRG10GLP01_SDTM_2018_06JUN_19")
	)
	
	dataFiles <- list.files(
		pattern = "\\.sas7bdat$",
		path = pathData, 
		full.names = TRUE
	)
	
	library(tools)
	# extract ADaM dataset name
	names(dataFiles) <- toupper(file_path_sans_ext(basename(dataFiles)))
	
	# import SAS datasets into R
	library(haven)
	dataList <- sapply(names(dataFiles), function(name){
		message("Load data for dataset: ", name)
		data <- read_sas(dataFiles[name])
		if(nrow(data) > 0){
			data <- cbind(data, ADAM = name)
			# column names in lower case for some datasets
			colnames(data) <- toupper(colnames(data))
		}else	warning("Dataset ", name, " is empty.")
		data
	}, simplify = FALSE)
	
	# bind datasets
	library(plyr)
	data <- plyr::rbind.fill(dataList)
	
	## extract label variables
	
	# extract labels of the variables
	library(glpgUtility)
	labelVars <- getLabelVars(dataList)

```

```{r createPlotModuleOfInterest}

	## subject information (metadata)
	dmPlots <- subjectProfileTextPlot(
		data = dataList$DM,
		vars = c("SEX", "AGE", "RACE", "COUNTRY", "ARM")
	)
	
	## medical history
	dmPlots <- subjectProfileTextPlot(
		data = dataList$MH,
		paramVar = "MHDECOD",
		paramValueVar = "MHOCCUR"
	)

	## adverse event: range
	
	head(dataList$AE)
	# AEPTCD: preferred term code
	aePlots <- subjectProfileRangePlot(
		data = dataList$AE,
		paramVar = "AETERM",
		subjectVar = "USUBJID",
		startVar = "AESTDY",
		endVar = "AEENDY",
		colorVar = "AESEV",
		labelVars = labelVars
	)
	
	## laboratory data
	
	head(dataList$LB)
	
	# prepare data for plots:
	dataLB <- dataList$LB
	# sort the categories (empty values '' becomes NA)
	dataLB$LBNRIND <- factor(dataLB$LBNRIND, levels = c("LOW", "NORMAL", "HIGH"))
	
	# create plot
	lbPlots <- subjectProfileEventPlot(
		data = dataLB,
		paramVar = "LBTEST",
		subjectVar = "USUBJID",
		timeVar = "LBDY",
		colorVar = "LBNRIND",
		labelVars = labelVars	
	)

```

```{r createReportWithAllModules}

	createReport(
			
	)

```



